In [17]:
import os
import shutil

path_archive = r'C:\Users\Nabil\Desktop\Softia_Work_Repos\SHUT\archive\archive'

dirs = os.listdir(path_archive)

for dir in dirs:
    if dir != '213' and dir != '214':
        files = os.listdir(path_archive + '\\' + dir)
        for file in files:
            if file.rfind('.') == -1:
                shutil.rmtree(path_archive + '\\' + dir + '\\' + file)

In [2]:
import paramiko
from scp import SCPClient
import shutil


def createSSHClient(server, port, user, password):
    client = paramiko.SSHClient()
    client.load_system_host_keys()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(server, port, user, password)
    return client


ssh = createSSHClient('192.168.10.77', 22, 'softia', 'Softia321+')
scp = SCPClient(ssh.get_transport())

scp.put(r'C:\Users\Nabil\Desktop\Softia_Work_Repos\SHUTRefonte\shut-refonte\ScriptLectureReleves\PD3',
        '/home/softia/shut/data', recursive=True)

shutil.rmtree(r'C:\Users\Nabil\Desktop\Softia_Work_Repos\SHUTRefonte\shut-refonte\ScriptLectureReleves\PD3')

In [29]:
import datetime
import pytz

time_z = '27/10/2024 02h01'
local = pytz.timezone("Europe/Paris")
time_m = datetime.datetime.strptime(time_z, '%d/%m/%Y %Hh%M')
local_dt = local.localize(time_m, is_dst=True)

utc_dt = local_dt.astimezone(pytz.utc)

print(time_m)
print(utc_dt.strftime('%Y-%m-%d %H:%M:%S'))

2024-10-27 02:01:00
2024-10-27 00:01:00

In [20]:
import pandas as pd

df = pd.read_csv('resultat_PD3_ana.csv')
df.head()

df['horodate'] = df[['horodate']].map(
    lambda x: datetime.datetime.strptime(x, '%d/%m/%Y %Hh%M').strftime('%Y-%m-%d %H:%M:%S'))

df.head()

              horodate          voie  mesure  mesure_brute evenement
0  2008-12-22 00:00:00    YAV_V1_PD3   32.29        3229.0         J
1  2008-12-22 00:00:00    QAV_V1_PD3    0.00           0.0         J
2  2008-12-22 00:00:00    VAV_V1_PD3    0.00           0.0         J
3  2008-12-22 00:00:00  YCO_VMER_PD3   33.50        3350.0         J
4  2008-12-22 00:00:00  QCO_VMER_PD3    1.26         126.0         J

In [6]:
list_stations_equipements = []
with open(f'Equipement_stations.csv', "r", encoding="utf-8") as f:
    
    dates_passage_API_stations = []
    lines = f.readlines()
    for index, line in enumerate(lines):
        if index > 0:
            items = line.strip('\n').split(';')
            station = items[0].strip(' ')
            date_passage = items[3].replace(u'\xa0', u'')
            list_stations_equipements.append(station)
            dates_passage_API_stations.append((station, date_passage))

In [9]:
list_stations_TUTL = []
with open(f'passage_TUTL.csv', "r", encoding="utf-8") as f:
    dates_passage_TU_stations = []
    lines = f.readlines()
    for index, line in enumerate(lines):
        if index > 0:
            items = line.strip('\n').split(';')
            station = items[0].strip(' ')
            date_passage = items[4].replace(u'\xa0', u'')
            list_stations_TUTL.append(station)
            dates_passage_TU_stations.append((station, date_passage))
print(dates_passage_TU_stations)

[('BA', '23/03/202303h00'), ('BBp', '28/02/2023'), ('BD', '26/03/202401h'), ('BGp', '13/03/202311h'), ('BM', '20/01/2024'), ('BRp', '18/09/2024'), ('CH', '27/10/2023 16h30'), ('CLp', '29/03/2023 11h00'), ('CV', '27/03/20248h'), ('DRp', '22/03/202311h'), ('DU', '17/01/2024'), ('FB', '20/02/2024'), ('FH', 'TOUJOURS'), ('GA', '13/04/2023 16h00'), ('GM', '14/03/2024'), ('GP', '23/03/2023 13h'), ('GR', '05/08/2024'), ('GYp', '04/03/202411h54'), ('HE', '27/10/2023 14h30'), ('JE', '27/02/2023'), ('JM', '31/01/2024'), ('KK', '20/05/2022'), ('LGp', '08/12/2023'), ('LR', '27/10/2023 15h30'), ('LVp', '07/12/2022'), ('MO', '19/01/2024'), ('MS', 'TOUJOURS'), ('MTp', '09/03/202311h'), ('NCp', '12/02/202417h'), ('NEp', '08/01/2024 11h'), ('NMp', '29/01/2024'), ('NPp', '21/02/20248h'), ('OUp', '28/02/2023'), ('PM', '20/03/2023'), ('PNp', '11/12/2023'), ('PO', '15/02/2024'), ('PS', 'TOUJOURS'), ('QM', '28/03/2024 12h'), ('RL', '19/01/2024'), ('RU', 'TOUJOURS'), ('RV', '08/02/2024'), ('SL', '28/02/2024 10h12'), ('TFp', '13/04/2023 12h00'), ('TH', '10/01/2024'), ('VIp', '27/02/2023'), ('VS', 'TOUJOURS')]

In [15]:
import os
list_stations = []
with open(f'ListeStations.csv', "r", encoding="utf-8") as f:
    lines = f.readlines()
    for index, line in enumerate(lines):
        if index > 0:
            items = line.strip('\n').split(';')
            station = items[1].strip(' ')
            list_stations.append(station)

list_info_TUTL = [x for x in list_stations if not x in list_stations_TUTL]
list_info_Equipement = [
    x for x in list_stations if not x in list_stations_equipements]
print(len(list_info_TUTL))
print(len(list_info_Equipement))

183
177

In [3]:
x = ('a', ('test', '-2', '1'))
y = (x[1][2], x[1][0])
print(y)

('1', 'test')

In [6]:
import pandas as pd

df = pd.read_csv('resultat_PD_tor.csv')
print(df.columns)

Index(['horodate', 'voie', 'mesure', 'mesure_brute', 'evenement'], dtype='object')

In [31]:
with open(f'ListeStations.csv', "r") as f:
    lines = f.readlines()
    for index, line in enumerate(lines):
        if index > 0:
            items = line.strip('\n').split(';')
            station = items[0].strip(' ')
            nom_station = items[1].strip(' ')
            user = items[3].strip(' ')
            print(station, nom_station, user)

101 101 Nabil
103 103 Nabil
105 105 Nabil
123 123 Nabil
124 124 Nabil
136 136 Nabil
137 137 Nabil
153 153 Nabil
156 156 Nabil
159 159 Nabil
161 161 Nabil
168 168 Nabil
169 169 Nabil
170 170 Nabil
171 171 Nabil
172 172 Nabil
173 173 Nabil
174 174 Nabil
175 175 Nabil
176 176 Nabil
177 177 Nabil
178 178 Nabil
179 179 Nabil
180 180 Nabil
181 181 Nabil
182 182 Nabil
183 183 Nabil
184 184 Yann
185 185 Yann
186 186 Yann
189 189 Yann
190 190 Yann
191 191 Yann
192 192 Yann
194 194 Yann
195 195 Yann
196 196 Yann
197 197 Yann
198 198 Yann
199 199 Yann
200 200 Yann
201 201 Yann
202 202 Yann
203 203 Yann
204 204 Yann
206 206 Yann
207 207 Yann
208 208 Yann
209 209 Yann
210 210 Yann
212 212 Yann
213 213 Yann
214 214 Yann
215 215 Yann
216 216 Yann
217 217 Yann
218 218 Yann
219 219 Yann
220 220 Yann
221 221 Yann
222 222 Yann
223 223 Yann
224 224 Yann
226 226 Yann
227 227 Yann
008 008 Nabil
009 009 Nabil
020 020 Nabil
028 028 Nabil
029 029 Nabil
037 037 Nabil
050 050 Nabil
061 061 Nabil
075 075 Nabil
088 088 Nabil
092 092 Nabil
AB1 AB Nabil
AC2 AC Nabil
AF2 AF Nabil
AN3 AN Nabil
AP3 AP Nabil
AS2 AS Nabil
AZ3 AZ Nabil
BA1 BA Nabil
BB5 BB Nabil
BD2 BD Nabil
BG5 BG Nabil
BM4 BM Nabil
BP3 BP Nabil
BR5 BR Nabil
BT2 BT Nabil
CA1 CA Nabil
CB2 CB Nabil
CH1 CH Nabil
CI2 CI Nabil
CL5 CL Nabil
CM2 CM Nabil
CN2 CN Nabil
CO2 CO Nabil
CR2 CR Nabil
CS1 CS Nabil
CT2 CT Nabil
CU3 CU Nabil
CV1 CV Nabil
CX1 CX Nabil
DB1 DB Nabil
DJ3 DJ Nabil
DR5 DR Nabil
DU6 DU Nabil
EB3 EB Nabil
EE3 EE Nabil
EN2 EN Nabil
ES3 ES Nabil
FA2 FA Nabil
FB3 FB Nabil
FH1 FH Nabil
FO3 FO Nabil
GA1 GA Nabil
GD1 GD Nabil
GE3 GE Nabil
GG3 GG Nabil
GI2 GI Nabil
GM3 GM Nabil
GO3 GO Nabil
GP1 GP Nabil
GR2 GR Nabil
GY5 GY Nabil
HB1 HB Nabil
HE1 HE Nabil
JE5 JE Nabil
JJ1 JJ Nabil
JM3 JM Nabil
JP1 JP Nabil
KK1 KK Nabil
KR1 KR Nabil
LE3 LE Nabil
LG5 LG Nabil
LI3 LI Nabil
LJ1 LJ Nabil
LP1 LP Nabil
LQ1 LQ Nabil
LR1 LR Nabil
LV5 LVp Nabil
LY1 LY Nabil
MA1 MA Nabil
MD2 MD Yann
ML1 ML Yann
MN2 MN Yann
MO1 MO Yann
MP4 MP Yann
MR2 MR Yann
MS1 MS Yann
MT5 MT Yann
MU1 MU Yann
MY1 MY Yann
NC5 NC Yann
NE5 NE Yann
NG3 NG Yann
NM5 NM Yann
NP5 NP Yann
NU1 NU Yann
OU5 OU Yann
P12 P12 Yann
P27 P27 Yann
P32 P32 Yann
P33 P33 Yann
PA1 PA Yann
PG1 PG Yann
PH1 PH Yann
PL1 PL Yann
PM1 PM Yann
PN5 PN Yann
PO1 PO Yann
PP2 PP Yann
PR1 PR Yann
PS1 PS Yann
PT1 PT Yann
PV3 PV Yann
PY2 PY Yann
QM2 QM Yann
QS2 QS Yann
RA3 RA Yann
RB5 RB Yann
RC3 RC Yann
RE2 RE Yann
RF1 RF Yann
RH1 RH Yann
RL1 RL Yann
RO2 RO Yann
RR1 RR Yann
RS1 RS Yann
RU1 RU Yann
RV2 RV Yann
RY0 RY Yann
SA1 SA Yann
SC1 SC Yann
SF3 SF Yann
SL5 SL Yann
SO1 SO Yann
SX1 SX Yann
TD1 TD Yann
TF5 TF Yann
TH1 TH Yann
TU2 TU Yann
UK1 UK Yann
VE1 VE Yann
VG2 VG Yann
VI5 VI Yann
VS1 VS Yann
VT1 VT Yann
VV3 VV Yann
XX1 XX Yann
ZD3 ZD Yann
PD3 PD Nabil

In [6]:
from utils import creer_repertoire_resultat

creer_repertoire_resultat('124')

['YUN_OV_124', '???']
['YUN_OV_124']
[]
Function 'creer_repertoire_resultat' took 19.2071 seconds to execute.

In [1]:
import pandas as pd

df = pd.read_csv('resultat_124_ana.csv')

df.head()

           horodate        voie  mesure  mesure_brute evenement TUTL
0  24/01/2012 15h58  YUN_OV_124    0.18            18             TU
1  25/01/2012 00h00  YUN_OV_124   99.99          9999         J   TU
2  25/01/2012 15h58  YUN_OV_124    0.18            18             TU
3  26/01/2012 00h00  YUN_OV_124   99.99          9999         J   TU
4  26/01/2012 15h58  YUN_OV_124    0.18            18             TU

In [5]:
voies = df['voie'].drop_duplicates().tolist()
print(voies)
voies = list(filter(lambda x: str(x).rfind('_') != -1, voies))
print(voies)

['YUN_OV_124', '???']
['YUN_OV_124']

In [3]:
df_unknown = df[df['voie'] == '???']
df_unknown.head()

                horodate voie  mesure  mesure_brute evenement TUTL
546806  16/02/2015 00h00  ???    0.17            17         J   TU
546807  16/02/2015 17h02  ???    0.17            17             TU
546808  16/02/2015 17h04  ???    0.17            17             TU
546809  16/02/2015 17h06  ???    0.17            17             TU
546810  16/02/2015 17h08  ???    0.17            17             TU

In [3]:
import os
path = r'C:\Users\Nabil\Desktop\Softia_Work_Repos\SHUTRefonte\DataSHUT'
directories = os.listdir(path)
try:
    for directory in directories:
        items = os.listdir(path + '/' + directory)
        for item in items:
            if item.endswith('.sql'):
                f = open(path + '/' + directory + '/' + item, mode="r")
                print(f.name)
                lines = f.readlines()
                for index, line in enumerate(lines):
                    if line.rfind('SELECT') != -1:
                        lines[index] = ' '
                lines = [x for x in lines if x != ' ']
                f.close()
                f = open(path + '/' + directory + '/' + item, mode="w")
                f.writelines(lines)
                f.close()
except Exception as e:
    print(e)

C:\Users\Nabil\Desktop\Softia_Work_Repos\SHUTRefonte\DataSHUT/AB/script_ab.sql
C:\Users\Nabil\Desktop\Softia_Work_Repos\SHUTRefonte\DataSHUT/AB/script_delete_ab.sql
C:\Users\Nabil\Desktop\Softia_Work_Repos\SHUTRefonte\DataSHUT/AC/script_ac.sql
[WinError 267] Nom de répertoire non valide: 'C:\\Users\\Nabil\\Desktop\\Softia_Work_Repos\\SHUTRefonte\\DataSHUT/bd4.mdb'

In [6]:
import os
path = r'C:\Users\Nabil\Desktop\Personal\uno\Historique'

dirs = os.listdir(path)
filename = path + '\\' + 'script_psql.sh'
myfile = os.open(filename, flags=os.O_RDWR | os.O_CREAT, mode=0o700)
for dir in dirs:
        if not dir.endswith('.sh'):
            print(dir)
            files = os.listdir(path + '\\' + dir)
            for file in files:
                if file.endswith('.sql'):
                    with open(filename, 'a') as f:
                        f.write(f'psql -U postgres -d shut_archive -f {path}\{dir}\{file} -o {path}\{dir}\{file.replace(".sql", ".log")}\n')
os.close(myfile)

JJ
LI